M48
; DRILL file {KiCad 7.0.5-7.0.5~ubuntu22.04.1} date wto, 6 cze 2023, 13:21:42
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-06T13:21:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-7.0.5~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.937Y-3.1102
X3.937Y-5.5118
X7.1752Y-3.1102
X7.1752Y-5.5118
T0
M30
